### ISSUE TITLE
Use soem-ng or soem

### ISSUE THREAD

**Issue by jespersmith** [OpenEtherCATsociety/soem-ng#2]
I'm looking at switching from the IgH ethercat master to SOEM. I'm currently investigating integrating SOEM in our code base. As we use Java, this requires writing a translation layer. I do not want to invest a large amount of time if soem-ng will replace soem in the short time.

What would the time frame be of soem-ng becoming viable or shall I push on with SOEM (current gen)?

**Comment by mheden** [comment]
We haven't got as far with `soem-ng` as we liked so if I where you I would go for `SOEM`. I hope for a beta of `soem-ng` during the autumn.

**Comment by jespersmith** [comment]
Ok, I'll implement a light C wrapper for the functions we use and use SOEM for now. That would make it easy to switch later.

**Comment by ghost** [comment]
Hi, jespersmith
I am Gopal working on SOEM as master to control multi-axes robot. We thought of switching from SOEM to IgH. My doubt is why are you switching from the IgH ethercat master to SOEM. Is there any limitation with IgH to work. I heard like IgH is more reliable and performs better as it is kernel level implementation. Please give your suggestions based on your experience which ll be great help.... Thank you in advance.

**Comment by jespersmith** [comment]
Hi Gopal,

We switched to SOEM because IgH is not very actively maintained anymore. While for a mature product this would generally not be a problem, the IgH ethercat needs kernel modules updated for the newest kernels. You want to trawl the mailing lists for patch sets that fix a bunch of issues as well. SOEM is a much lighter wrapper using a stable API into the kernel so even without maintenance it'll last longer in my opinion. Also there is an option for other OSes.,

Performance might be a bit better, but we have seen no performance issues with SOEM so far, especially setting coalsce settings (see the text file in SOEM). The IgH master does all the PDO configuration for you, so it is easier to use. SOEM is also easier to bundle as a .so with our software.

Jesper
